import { Pacifico, Sriracha } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import Footer from "./_components/footer/Footer";


const pacifico = Pacifico({
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-pacifico",
});

const sriracha = Sriracha({
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-sriracha",
});

export const metadata = {
  title: "Coffero",
  description: "Generated by create next app",
  icons: {
    icon: "/images/pic.png",   
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${pacifico.variable} ${sriracha.variable}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
